---
apiVersion: topology.node.k8s.io/v1
kind: NodeResourceTopology
metadata:
  name: node1
topologyPolicies:
  - singleNumaNode
zones:
  - name: node-0
    type: Node
    resources:
      - name: cpu
        capacity: 20
        allocatable: 10
      - name: vendor/nic1
        capacity: 3
        allocatable: 3
  - name: node-1
    type: Node
    resources:
      - name: cpu
        capacity: 30
        allocatable: 15
      - name: vendor/nic2
        capacity: 6
        allocatable: 6
  - name: node-2
    type: Node
    resources:
      - name: cpu
        capacity: 30
        allocatable: 15
      - name: vendor/nic1
        capacity: 3
        allocatable: 3
  - name: node-3
    type: Node
    resources:
      - name: cpu
        capacity: 30
        allocatable: 15
      - name: vendor/nic1
        capacity: 3
        allocatable: 3
